name: CI

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README
        shell: bash
        run: |
          echo "Añadida feature: ${{ github.head_ref || github.ref_name }}" >> README.md

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add README.md
          git commit -m "Update README with feature" || echo "No changes to commit"
          git pull --rebase origin ${{ github.head_ref || github.ref_name }}
          git push origin HEAD:${{ github.head_ref || github.ref_name }}

  validate-dev:
    needs: update-readme
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate DEV token
        env:
          DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
        shell: powershell
        run: |
          if ($env:DEV_TOKEN -eq $env:LOCAL_DEV_TOKEN) {
            Write-Host "Los tokens coinciden"
          } else {
            Write-Host "Los tokens NO coinciden"
            exit 1
          }
