name: Prueba secrets y variables localesv4

on:
  push:

jobs:
  comprobar-token:
    runs-on: self-hosted

    steps:
      - name: Comprobar variables
        shell: powershell
        env:
          DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
        run: |
          Write-Host "DEV_TOKEN presente: $([string]::IsNullOrEmpty($env:DEV_TOKEN) -eq $false)"
          Write-Host "LOCAL_DEV_TOKEN presente: $([string]::IsNullOrEmpty($env:LOCAL_DEV_TOKEN) -eq $false)"
          Write-Host "Longitud DEV_TOKEN: $($env:DEV_TOKEN.Length)"
          Write-Host "Longitud LOCAL_DEV_TOKEN: $($env:LOCAL_DEV_TOKEN.Length)"

          if ($env:DEV_TOKEN -eq $env:LOCAL_DEV_TOKEN) {
            Write-Host "Los tokens coinciden."
          } else {
            Write-Host "Los tokens NO coinciden."
            exit 1
          }